#include <stdint.h>
#include <sys/types.h>

#include "stm32f4xx.h"

#include "bsp_fsmc_sram.h"
#include "bsp_nor_flash.h"
#include "ff.h"
#include "bsp_sdio_sd.h"
#include "bsp_reset.h"


// ---------------------------------------------------------------------------- //

// The following symbols are constructs generated by the linker, indicating
// the location of various points in the "Memory regions initialisation arrays".
// These arrays are created by the linker via the managed linker script
// of each RW data mechanism. It contains the load address, execution address
// and length section and the execution and length of each BSS (zero
// initialised) section.
extern unsigned int __data_regions_array_start;
extern unsigned int __data_regions_array_end;
extern unsigned int __bss_regions_array_start;
extern unsigned int __bss_regions_array_end;

static FATFS fs; /* Work area (file system object) for logical drives */



extern void main (void);
void _start (void);

inline void
__attribute__((always_inline))
__initialize_data (unsigned int* from, unsigned int* region_begin,
           unsigned int* region_end)
{
  // Iterate and copy word by word.
  // It is assumed that the pointers are word aligned.
  unsigned int *p = region_begin;
  while (p < region_end)
    *p++ = *from++;
}

inline void
__attribute__((always_inline))
__initialize_bss (unsigned int* region_begin, unsigned int* region_end)
{
  // Iterate and clear word by word.
  // It is assumed that the pointers are word aligned.
  unsigned int *p = region_begin;
  while (p < region_end)
    *p++ = 0;
}

void __attribute__ ((section(".after_vectors"),noreturn))
_start (void)
{
    SystemInit();
    SystemCoreClockUpdate();

    /*FSMC SRAM 初始化
     *  容量：2MB*/
    bsp_InitExtSRAM();

    /*FSMC NorFlash 初始化
     * 容量：4MB*/
    bsp_InitNorFlash();


	// Copy the data sections from flash to SRAM.
    for (unsigned int* p = &__data_regions_array_start;
            p < &__data_regions_array_end;)
    {
        unsigned int* from = (unsigned int *) (*p++);
        unsigned int* region_begin = (unsigned int *) (*p++);
        unsigned int* region_end = (unsigned int *) (*p++);

        __initialize_data (from, region_begin, region_end);
    }

    // Zero fill all bss segments
    for (unsigned int *p = &__bss_regions_array_start;
            p < &__bss_regions_array_end;)
    {
        unsigned int* region_begin = (unsigned int*) (*p++);
        unsigned int* region_end = (unsigned int*) (*p++);
        __initialize_bss (region_begin, region_end);
    }

    /*初始化micro SD卡*/
    SD_NVIC_Configuration();
    f_mount(0,&fs);

	main();

	cpu_reset();

	while(1);
}

